Change install script

diff --git a/script/install b/script/install
--- a/script/install
+++ b/script/install
@@ -1,4 +1,13 @@
 #!/bin/bash
 
-curl https://raw.githubusercontent.com/tuist/tuist/master/bin/tuistenv > /usr/local/bin/tuist
+URL=$( curl -s "https://api.github.com/repos/tuist/tuist/releases/latest" \
+   | jq -r '.assets[] | select(.name=="tuistenv") | .browser_download_url' )
+if [ "$URL" != "" ]; then
+  echo "Downloading tuist from $URL"
+else
+  echo "Couldn't find tuistenv on the latest release"
+  exit 1
+fi
+
+curl "$URL" > /usr/local/bin/tuist
 chmod +x /usr/local/bin/tuist
